### ISSUE TITLE
Anonymous users

### ISSUE THREAD

**Issue by JoshSmith** [kayako/ember-launch-darkly#18]
How are you currently handling anonymous users in your use of the addon?

My initial thoughts are to do something like the following:

- In my application route's `beforeModel`
  - Generate a UUID for every visitor
  - Store the UUID in the cookie store
  - Attempt to load my current user (using `ember-simple-auth`)
- In my application route's `model`
  - Initialize LaunchDarkly
    - with the user, if available
    - with the anonymous user, using the UUID from the cookie store (and also setting the `anonymous` key)

There's no way to ensure that the anonymous users will be _the same_ users on repeat visits, but it makes it much more likely that they won't be served different UIs (if we even used feature flags for anonymous users).

I'm curious if you do something similar.

I know it's a bit outside the scope of this addon per se, but it would be nice to have some guides about some best practices here. Would be happy to put something together if we agree what is actually a best practice! 😂 

Thanks in advance!

**Comment by achambers** [comment]
Hi @JoshSmith . Thanks for your patience. In all honesty, I missed this issue and only stumbled across it by chance just now. So, apologies for that.

So, we basically do the following:

1. For unauthenticated routes, for which we really only have the login page, we `initialize` the user with `anonymous: true`. We have a multi tenant site, and generally won't be enabling features on a per user basis but more of a per tenant basis. When initializing we actually use the host domain as the unique key at this point.

2. When a user logs in we `identify` them using their ID. We also pass their tenant as a custom field so we continue to enable flags on a per tenant basis. But we can go down to the per user level if we need to.

Hope that answers your question. If there is any other light I can shed on how we do things, please let me know :)

**Comment by achambers** [comment]
@JoshSmith Im going to close this for now as it's not really an issue. If you think it should be re-opened, by all means do so 😄
