### ISSUE TITLE
The plugin function launchDarklyVariationHelperPlugin didn't export a Plugin instance

### ISSUE THREAD

**Issue by patcoll** [kayako/ember-launch-darkly#20]
I haven't looked into this very deeply, but I wanted to put this here as a placeholder for conversation.

I added this addon to our Ember app (Node 6.11.1, Ember 2.11.0) with the right configuration, and when building the app I get the following error and the entire build fails. It even fails without the config on the ENV.

I've tried "nombom" and still with the same result. I checked out the `ember-launch-darkly` repo and added an `ember-try` case for 2.11.0 and all tests pass. So it might have to do with the unique setup we have.

Has anyone seen any error like this before? From a quick Google search, I found some similar errors and saw comments about a discrepancy between Babel 5 and 6. Our app uses `ember-cli` 2.11.0, which doesn't use `ember-cli-babel` 6.x, so I wonder if that's related somehow?

Any thoughts would be greatly appreciated! I'll be digging into this more.

```
Build failed.
File: ember-ajax/-private/promise.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel] failed with:
TypeError: The plugin function launchDarklyVariationHelperPlugin({ types: t }) {
  return {
    name: 'launch-darkly-variation-helper',
    visitor: {
      Program: {
        enter(path, state) {
          let variationImport = _findVariationHelperImport(path, t);

          if (variationImport && _isReferenced(variationImport, t)) {
            state.variationHelperReferenced = true;
          }
        },

        exit(path, state) {
          let variationImport = _findVariationHelperImport(path, t);

          if (variationImport) {
            _removeSpecifierOrImport(variationImport, t);

            if (state.variationHelperReferenced) {
              _insertServiceImport(path, t);
            }
          }
        }
      },

      Identifier(path, state) {
        if (path.referencesImport(MODULE_NAME, MEMBER_NAME)) {
          let parentCallExpression = path.findParent(p => t.isCallExpression(p));
          let key = parentCallExpression.get('arguments.0').node.value;
          parentCallExpression.replaceWith(_build(key, t));

          let { parent, type } = _findParent(parentCallExpression, t);

          switch (type) {
            case 'computed-property': {
              let dependentKey = `${SERVICE_PROPERTY_NAME}.${key}`;

              if (_shouldInjectDependentKey(key, parent, t)) {
                parent.node.arguments.unshift(t.stringLiteral(dependentKey));
              }

              let fn = parent.get('arguments').find(a => t.isFunctionExpression(a));

              if (fn && !_containsServiceDeclaration(fn, t)) {
                _insertServiceDeclaration(fn, t);
              }

              return;
            }
            case 'function': {
              _insertServiceDeclaration(parent, t);
              return;
            }
          }
        }
      },

      CallExpression(path, state) {
        if (state.variationHelperReferenced) {
          _insertServiceInjection(path, t);
        }
      }
    }
  };
} didn't export a Plugin instance
    at PluginManager.validate (<app>/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (<app>/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (<app>/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (<app>/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (<app>/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (<app>/node_modules/broccoli-babel-transpiler/index.js:107:21)
    at Babel.processString (<app>/node_modules/broccoli-babel-transpiler/index.js:206:25)
    at Promise.then.result.output (<app>/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (<app>/node_modules/rsvp/dist/rsvp.js:588:5)
    at new Promise (<app>/node_modules/rsvp/dist/rsvp.js:1076:31)

The broccoli plugin was instantiated at:
    at Babel.Plugin (<app>/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (<app>/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (<app>/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at EmberApp._addonTree (<app>/node_modules/ember-cli/lib/broccoli/ember-app.js:940:29)
    at EmberApp._processedVendorTree (<app>/node_modules/ember-cli/lib/broccoli/ember-app.js:974:20)
    at EmberApp._processedExternalTree (<app>/node_modules/ember-cli/lib/broccoli/ember-app.js:1005:21)
    at EmberApp.appAndDependencies (<app>/node_modules/ember-cli/lib/broccoli/ember-app.js:1114:30)
    at EmberApp.javascript (<app>/node_modules/ember-cli/lib/broccoli/ember-app.js:1244:34)
    at EmberApp.toArray (<app>/node_modules/ember-cli/lib/broccoli/ember-app.js:1674:10)
    at EmberApp.toTree (<app>/node_modules/ember-cli/lib/broccoli/ember-app.js:1696:30)
```

**Comment by achambers** [comment]
@patcoll Thanks for this. I suspect the Babel version is going to be your problem here. This plugin was written for Babel 6 currently. Would you have any interest in contributing a Babel 5 version? I'm more than happy to help you along the way if need be.

**Comment by patcoll** [comment]
@achambers Ok cool. We also have an Ember upgrade in progress, albeit moving slowly. Trying to decide which one to prioritize at this point.

Do you have an idea of what would be involved in that, in general? I'm not sure what the differences are for plugin development purposes.

**Comment by achambers** [comment]
@patcoll asked:

> Do you have an idea of what would be involved in that, in general?

Mate, I'm afraid I don't. I focussed on Babel 6 as that satisfied our use case. I'm not intimately familiar with the intricacies of 5 vs 6. I can't imagine it'd be too different and it should be easy enough to get an idea using astexplorer.net.

Seeing as we don't use Babel < 6 it's hard to prioritise it right now but I'd be more than happy to jump on a call with you or something if you decide to have a crack. Or we can pair for a short while to get you moving forward.

**Comment by achambers** [comment]
@patcoll A friendly ping to see what your thoughts are on this issue. I won’t be implementing support for Babel < 6 but am not than happy to accept PR for it. 

I’m going to close this issue unless you feel there is a reason not to.

**Comment by patcoll** [comment]
@achambers We've focused on upgrading our app code base to 2.13.x for now, which includes support under the covers for Babel 6. It's not worth it for us to provide support for a Babel-5-compatible version of the addon.

Alternatively, it could be really helpful for future interested parties to document Babel-6-only compatibility in the README somewhere 😄 

Closing this

**Comment by achambers** [comment]
@patcoll said:

> It's not worth it for us to provide support for a Babel-5-compatible version of the addon.

Same here :)

> Alternatively, it could be really helpful for future interested parties to document Babel-6-only compatibility in the README somewhere 😄

Great idea. Will do so when I get a chance. Unless you beat me to it with a PR yourself ;)
